package:
        name: idlpy
        version: 0.2.3
source:
        path: ../
        #git_url: https://github.com/kwodzicki/idlpy.git
        #git_rev:
requirements:
        build:
                - python
                - setuptools
                - Cython
                - numpy
        run:
                - python

